### ISSUE TITLE
Version 2.0 Task List

### ISSUE THREAD

**Issue by metafloor** [metafloor/bwip-js#145]
The task list for the 2.0 release.  Most are already started, just not finalized.  If you have any wants or questions, please post.

  - [x] Single file UMD
  - [x] Promise or callback
  - [x] FreeType replacement
  - [x] Embedded OCR fonts
  - Output
      - [x] PNG (node.js only, default)
      - [x] Canvas (browser only, default)
      - [ ] SVG
      - [ ] Raw (enhanced BWIPP data)
      - [ ] Drawing api
        - init(w, h, opts)
        - rect(x, y, w, y, opts)
        - poly(pts, opts)
        - ellipse(x, y, rx, ry, opts)
        - text(x, y, t, opts)
		- end()
  - [x] JavaScript maxicode renderer (renmaximatrix)
  - [ ] BWIPP 2D renderer (renmatrix)
  - [x] Background color bug

**Comment by metafloor** [comment]
JAB Code profiling shows CPU pegged for ~4 seconds.  Needs aggressive trace and peephole optimization to make it production safe.
![image](https://user-images.githubusercontent.com/385436/69449049-28509500-0d17-11ea-8d6e-75c88c1573c9.png)

**Comment by terryburton** [comment]
Don't include JAB for the time being. The standard is going through heavy changes. The bitwise LDPC encoding is never going to be performance on a PS VM.

**Comment by metafloor** [comment]
Just a short notice that the 2.0 release of bwip-js is on github and npm.  Please let me know if you face any issues with upgrading.
